### ISSUE TITLE
!wiki command not working

### ISSUE THREAD

**Issue by squarepear** [rey2952/RoverBot#8]
IT WONT SEARCH!!!

**Comment by angeloanan** [comment]
Need to fix promises. 

_**plznextimeincludedetails :d** _ 


_Sent from my Redmi 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by angeloanan** [comment]
Issue found: Double variable named the same
```js
this.Command = function (data) {
  if (data.args.length > 0) {
    wikia.getSearchList({'query': data.args.join(' ')}).then(function (data) {
```

Still doesn't work tho. It's because of the message sending part of the bot.

**Comment by angeloanan** [comment]
**SUGGESTION**: Making the output RichEmbed

**Comment by squarepear** [comment]
Fixed!
